[menu]
  [[menu.social]]
    # 唯一标识符
    identifier = "github"
    # 名称
    name = "github"
    # url地址
    url = "https://github.com/lmhlll"
    # 权重 越小越靠前
    weight = 1
[author]
  name = "Liminghui"
  email = "894194906@qq.com"
  description = "李铭慧"
  avatar = "https://s.gravatar.com/avatar/7b5a0b07a98895278cfa862b1f32ae8f?s=200&r=g&d=retro"
